--SELECT D.ID, D.NAME, D.NOTES, D.* FROM OMS_DOCUMENT D WHERE ID IN (SELECT MAX(ID) FROM OMS_DOCUMENT);
SELECT ID, NAME, NOTES, D.* FROM OMS_DOCUMENT D WHERE ID=9161793;
SELECT NOTES FROM OMS_CLAIM;
--update nexus_gis.oms_document set notes = 'prueba' || chr(13) || chr(13) || 'fin prueba;' where id=9161793;
UPDATE NEXUS_GIS.OMS_CUST_SITUATION_INTERF SET TEL_CAMP = '9*1540793878' WHERE CLAIM_ID = 26173023;
UPDATE NEXUS_GIS.OMS_CUST_SITUATION_INTERF SET TEL_CAMP = '9*1559479562' WHERE CLAIM_ID = 26173505;
UPDATE NEXUS_GIS.OMS_CUST_SITUATION_INTERF SET TEL_CAMP = '9*1565783954' WHERE CLAIM_ID = 26173648;
UPDATE NEXUS_GIS.OMS_CUST_SITUATION_INTERF SET TEL_CAMP = '9*1523902386' WHERE CLAIM_ID = 26173606;

DOC: 9161793 > RECL: 26173023 > MARTIN FONTANA     > '9*1540793878'
DOC: 9161793 > RECL: 26173648 > HERNY PADILLA      > '9*1565783954'
DOC: 9161793 > RECL: 26173606 > SERGIO MICHELOTTI  > '9*1523902386'
DOC: 9161793 > RECL: 26173505 > MARTIN LEROY       > '9*1559479562'

--DOC CON 1000 RECLAMOS

--DOC: 9161793 > RECL: 26173128 > MARTIN LEROY       > '9*1559479562' > CAMPO OBS NULO
--

SELECT OMS_CUST_SITUATION_INTERF.CLAIM_ID,
		substr(OMS_CLAIM.NAME,11) "NumeroDelReclamo",
		OMS_CUST_SITUATION_INTERF.DOCUMENT_ID,
		OMS_CUST_SITUATION_INTERF.FSCLIENTID,
		OMS_CUST_SITUATION_INTERF.FULLNAME,
		OMS_CUST_SITUATION_INTERF.TEL_CAMP,
		OMS_CUST_SITUATION_INTERF.LAST_STATE_DATE,
		(CASE OMS_CLAIM.HAZARD_LEVEL_ID WHEN 10701 THEN 'SI' ELSE 'NO' END) AS "ContienePeligro",
		TRIM((SELECT SPRGCODES.CODENAME FROM NEXUS_GIS.SPRGCODES WHERE SPRGCODES.CODEID = TO_NUMBER(SPRCLIENTS.CUSTATT21))) AS "Sensible",
		(SELECT COUNT(OMS_CLAIM.NAME) FROM NEXUS_GIS.OMS_CLAIM WHERE OMS_CLAIM.PROPERTY_VALUE = OMS_CUST_SITUATION_INTERF.FSCLIENTID
		AND OMS_CLAIM.CREATION_TIME > SYSDATE - 15) AS "RecAnt",
		OMS_CLAIM.COUNT_REITERATION AS "Reiteraciones",
		(SELECT FDL_CLAIM_REASON.DESCRIPTION FROM NEXUS_GIS.FDL_CLAIM_REASON WHERE FDL_CLAIM_REASON.ID = OMS_CLAIM.REASON_ID) AS "Motivo",
		(SELECT FDL_CLAIM_SUBREASON.DESCRIPTION FROM NEXUS_GIS.FDL_CLAIM_SUBREASON WHERE FDL_CLAIM_SUBREASON.ID = OMS_CLAIM.SUBREASON_ID) AS "Submotivo",
		OMS_DOCUMENT.NAME AS "NumeroDelDocumento",
		OMS_DOCUMENT.CREATION_TIME   AS "InicioDelCorte",
		(SELECT LAST_MODIFIED_TIME FROM NEXUS_GIS.OMS_CLAIM WHERE OMS_CLAIM.ID=OMS_CUST_SITUATION_INTERF.CLAIM_ID) AS "FechaUltimoReclamo",
		(SELECT TRIM(AMAREAS.AREANAME) FROM NEXUS_GIS.AMAREAS WHERE AMAREAS.AREAID = SPRCLIENTS.LEVELTHREEAREAID) AS "AreaOperativa",
		(SELECT TRIM(AMAREAS.AREANAME) FROM NEXUS_GIS.AMAREAS WHERE AMAREAS.AREAID = SPRCLIENTS.LEVELONEAREAID) AS "Localidad",
		(SELECT TRIM(AMAREAS.AREANAME) FROM NEXUS_GIS.AMAREAS WHERE AMAREAS.AREAID = SPRCLIENTS.LEVELTWOAREAID) AS "Partido",
		OMS_DOCUMENT.MODEL_ELEMENT_CHAIN  AS "JerarquiaElectrica",
		OMS_DOCUMENT.COUNT_CLAIM AS "CantidadReclamos",
		TRIM(SPRCLIENTS.FULLADDRESS) AS "Direccion",
		(SELECT FDL_HAZARD_LEVEL.DESCRIPTION FROM NEXUS_GIS.FDL_HAZARD_LEVEL WHERE FDL_HAZARD_LEVEL.ID = OMS_CLAIM.HAZARD_LEVEL_ID) AS "NivelDePeligro",
		OMS_DOCUMENT.NOTES AS "Observaciones",
		OMS_DOCUMENT.HIGHER_DANGER_LEVEL AS "MayorNivelDePeligros",
		OMS_DOCUMENT.MWMSTATE AS "EstadoMWN",
		OMS_CLAIM.IS_VIP AS "VIPs",
		TRIM(OMS_DOCUMENT.HIGHER_FARE) AS "HigherFare"
		FROM NEXUS_GIS.OMS_CUST_SITUATION_INTERF, NEXUS_GIS.SPRCLIENTS, NEXUS_GIS.OMS_DOCUMENT, NEXUS_GIS.OMS_CLAIM
		WHERE OMS_CUST_SITUATION_INTERF.FSCLIENTID = SPRCLIENTS.FSCLIENTID
		AND OMS_CUST_SITUATION_INTERF.DOCUMENT_ID = OMS_DOCUMENT.ID
		AND OMS_CUST_SITUATION_INTERF.CLAIM_ID = OMS_CLAIM.ID
		AND OMS_DOCUMENT.ID= OMS_CUST_SITUATION_INTERF.DOCUMENT_ID
		AND OMS_DOCUMENT.LAST_STATE_ID <= 3
		AND NVL(OMS_CUST_SITUATION_INTERF.NRO_CAMP,0) = 0
		AND NVL(OMS_CUST_SITUATION_INTERF.LAST_ACTION,0) = 0
		AND OMS_CUST_SITUATION_INTERF.LAST_STATE_ID = 2
		AND OMS_CUST_SITUATION_INTERF.TEL_CAMP IS NOT NULL
		AND OMS_CUST_SITUATION_INTERF.FE_INI_CAMP IS NULL
		AND OMS_CUST_SITUATION_INTERF.CLAIM_ID = OMS_CLAIM.ID
		AND ROWNUM <= 1000
--    AND OMS_DOCUMENT.ID=9161793