D-23-11-011446
/*CORTES MT*/
SELECT ID, NAME, CREATION_TIME, LAST_STATE_ID, TYPE_ID, COUNT_INIT_AFFECTED_CUSTOMERS, AFFECTED_CLIENTS FROM OMS_DOCUMENT WHERE NAME='D-23-11-011446';
SELECT * FROM TABLA_ENREMTAT_GEN WHERE NRO_DOCUMENTO='D-23-11-011446';
SELECT ELEMENT_ID, CT_AFECTADO, CANT_AFECTACIONES FROM TABLA_ENREMTAT_DET WHERE NRO_DOCUMENTO='D-23-11-011446';
SELECT * FROM WS_ENREMTAT_LOG WHERE NRO_DOCUMENTO='D-23-11-011446';
SELECT a.ID,trunc(b.creation_time),trunc(sysdate) FROM NEXUS_GIS.TABLA_ENREMTAT_GEN A,NEXUS_GIS.OMS_DOCUMENT B where B.NAME='D-23-11-011446';

/*CORTES AT*/
SELECT * FROM WSENRE_CORTESAT WHERE NRO_DOCUMENTO='D-23-11-011446';
SELECT * FROM WSENRE_CORTESAT_LOG WHERE ID_DOCUMENTO IN (SELECT ID_DOCUMENTO FROM WSENRE_CORTESAT WHERE NRO_DOCUMENTO='D-23-11-011446');

SELECT * FROM TABLA_ENREMTAT_DET WHERE NRO_DOCUMENTO<>'D-23-11-011446' and CT_AFECTADO='40516' order by fecha_documento desc;

/*AFECTACIONES*/
SELECT DISTINCT
  ARO.DOCUMENT_ID
  , O.OBJECTID
  ,(SELECT TRIM(LINKVALUE) CT FROM NEXUS_GIS.SPRLINKS WHERE LOGIDTO=0 AND OBJECTID = O.OBJECTID AND LINKID=1198) CT
  , AE.COUNT_PROPERTIES
  , ARO.TIME INICIO
  , AROR.TIME FIN
  , ARO.OPERATION_ID
  , AROR.OPERATION_ID
--  ,ARO.AFFECT_TIME TIAFEINI
--  ,AROR.AFFECT_TIME TIAFEFIN
  ,AE.LAST_MODIFIED_DATE
  ,(SELECT EVENTO_CONFIRMADO FROM NEXUS_GIS.IDMS_DOCUMENTO_INFO WHERE ID_DOCUMENTO=ARO.DOCUMENT_ID) CONFIRMADO
FROM 
  SPROBJECTS O
  ,OMS_AFFECTED_ELEMENT AE
  ,OMS_AFFECT_RESTORE_OPERATION ARO
  ,OMS_AFFECT_RESTORE_OPERATION AROR
WHERE
  ARO.DOCUMENT_ID IN (SELECT ID FROM OMS_DOCUMENT WHERE NAME='D-23-11-011446')
--  AND O.OBJECTID IN (61797462)
  AND O.OBJECTNAMEID=AE.ELEMENT_ID
  AND AE.AFFECT_ID=ARO.ID
  AND AE.RESTORE_ID=AROR.ID(+)
  AND (SELECT TRIM(LINKVALUE) CT FROM NEXUS_GIS.SPRLINKS WHERE LOGIDTO=0 AND OBJECTID = O.OBJECTID AND LINKID=1198) IS NOT NULL
--  AND AE.COUNT_PROPERTIES>0
  AND O.OBJECTID=82910861
ORDER BY
  (SELECT TRIM(LINKVALUE) CT FROM NEXUS_GIS.SPRLINKS WHERE LOGIDTO=0 AND OBJECTID = O.OBJECTID AND LINKID=1198)
  , ARO.TIME
  , AROR.TIME
;

/*
BUSCO LAS OPERACIONES
*/
SELECT 
  D.NAME
  ,D.ID
  ,D.CREATION_TIME  D_CREATION_TIME
--  ,O.ID
  ,O.CREATION_TIME  O_CREATION_TIME
  ,O.NOTES
--  ,ARO.ID
  ,ARO.AFFECT_TIME  ARO_AFFECT_TIME
  ,ARO.IS_RESTORE
  ,AE.IS_AFFECTED
  ,AE.ELEMENT_ID
  ,AE.COUNT_PROPERTIES
  ,(SELECT TRIM(LINKVALUE) CT FROM NEXUS_GIS.SPRLINKS WHERE OBJECTID = OJ.OBJECTID AND LINKID=1198) CT
  ,AE.RESTORE_ID
  ,ARO.TIME INI
  ,(SELECT TIME FROM OMS_AFFECT_RESTORE_OPERATION WHERE ID=AE.RESTORE_ID) FIN
FROM 
  OMS_DOCUMENT D 
  ,OMS_OPERATION O
  ,OMS_AFFECT_RESTORE_OPERATION ARO
  ,OMS_AFFECTED_ELEMENT AE
  ,SPROBJECTS OJ
WHERE 
  D.ID IN (SELECT ID FROM OMS_DOCUMENT WHERE NAME='D-23-11-011446')
  AND D.ID=O.DOCUMENT_ID
  AND O.ID=ARO.OPERATION_ID
  AND ARO.ID=AE.AFFECT_ID(+)
  AND AE.ELEMENT_ID=OJ.OBJECTID(+)

ORDER BY O.ID
;


SELECT AROR.TIME 
FROM 
  OMS_AFFECT_RESTORE_OPERATION ARO
  ,OMS_AFFECTED_ELEMENT AE
  ,OMS_AFFECT_RESTORE_OPERATION AROR
WHERE 
  ARO.ID=AE.AFFECT_ID
  AND AE.RESTORE_ID=AROR.ID
  AND ARO.DOCUMENT_ID=11516825
  AND AE.ELEMENT_ID=88336952


;

/*Busco CT por NextID*/
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 61844448;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 67117908;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 67205951;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 67499463;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 67525048;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 71335938;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 74962154;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 81952125;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 82924613;
SELECT OBJECTID,NEXTID FROM NEXUS_GIS.SPROBJECTS WHERE SPRID=1293 AND OBJECTID = 90926081;

SELECT TRIM(linkvalue) FROM NEXUS_GIS.SPRLINKS WHERE objectid =61844448 AND linkid=1198;
SELECT TRIM(LINKVALUE) FROM NEXUS_GIS.SPRLINKS WHERE OBJECTID =90926081 AND LINKID=1198;



SELECT * FROM NEXUS_CCYB.CLIENTES_CCYB WHERE CUENTA='6065559605';
SELECT * FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID='6065559605';
SELECT * FROM NEXUS_GIS.OMS_CLAIM WHERE PROPERTY_VALUE='6065559605' AND LAST_STATE_ID NOT IN(3);





/*Busca cts at seleccionados en portal vs los que se cargaron en det*/

SELECT * FROM WSENRE_CORTESAT WHERE MARCA=1;
SELECT * FROM TABLA_ENREMTAT_GEN WHERE NRO_DOCUMENTO='D-22-01-000071';
SELECT * FROM TABLA_ENREMTAT_DET WHERE NRO_DOCUMENTO='D-23-10-036783';
SELECT * FROM WSENRE_CORTESAT_LOG WHERE ID_DOCUMENTO IN (SELECT ID FROM OMS_DOCUMENT WHERE NAME='D-23-10-036785') ORDER BY LOGID;

/*
D-23-05-071151
D-23-11-011446

document_id: 11162269
name: D-23-11-011446
cant cts: 417
cant cts >0 afe: 387
cant afe: 36999
cant cts en det: 0

document_id: 11141561
name: D-23-11-011446
cant cts: 243
cant cts >0 afe: 232
cant afe: 16523
cant cts en det: 0




*/
















