SET SERVEROUTPUT ON
declare

V_CUENTA VARCHAR2(30):= RPAD ('0460000000', 30);
V_OBJECT_NAME_ID_CUSTOMER NEXUS_GIS.SPROBJECTS.OBJECTNAMEID%TYPE;
V_DOCUMENTID NEXUS_GIS.OMS_DOCUMENT.ID%TYPE;
V_DOC NEXUS_GIS.OMS_DOCUMENT.NAME%TYPE;

begin
    SELECT OBJECTS.OBJECTNAMEID
    INTO v_object_name_id_customer
    FROM    sprlinks links
      INNER JOIN sprobjects objects ON OBJECTS.OBJECTID = LINKS.OBJECTID
    WHERE  
      links.linkvalue = V_CUENTA
      AND links.linkid = 407
      AND links.logidto = 0
      AND ROWNUM = 1;
                    
    SELECT ARO.ID
    INTO v_documentid
    FROM 
      NEXUS_GIS.SPROBJECTS O,
      NEXUS_GIS.OMS_AFFECTED_ELEMENT AE,
      NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO,
      NEXUS_GIS.OMS_DOCUMENT D
    WHERE
      1=1
      AND O.OBJECTNAMEID=AE.ELEMENT_ID
      AND AE.AFFECT_ID=ARO.ID
      AND O.OBJECTNAMEID=V_OBJECT_NAME_ID_CUSTOMER
      AND ARO.DOCUMENT_ID=D.ID
      AND d.status = 0
      AND AE.IS_AFFECTED = 1
      AND ROWNUM = 1
      ;
   
  SELECT NAME INTO V_DOC FROM OMS_DOCUMENT WHERE ID=    V_DOCUMENTID;      

  DBMS_OUTPUT.PUT_LINE('cuenta: '||V_CUENTA);
  DBMS_OUTPUT.PUT_LINE('objectid: '||V_OBJECT_NAME_ID_CUSTOMER);
  DBMS_OUTPUT.PUT_LINE('documentid: '||V_DOCUMENTID);
  DBMS_OUTPUT.PUT_LINE('nro doc: '||V_DOC);
  
END;

   
