set serveroutput on
DECLARE
	PASO VARCHAR2(7):= NULL;
BEGIN   
	BEGIN
		PASO:= 'MOD';
		NEXUS_GIS.INFORMACION_ENREMTAT.MODIFICA_DOCUMENTOS;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.INFORMACION_ENREMTAT.MODIFICA_DOCUMENTOS');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'GEN';		
		NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_GEN;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_GEN');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'DFO';	
		NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_DET;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_DET');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'DPR';	
		NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_DET_PRG;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.INFORMACION_ENREMTAT.INSERTA_DOCUMENTOS_DET_PRG');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'DELSACR';	
		NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.SCADA_AGATA_CON_RECLAMO;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.SCADA_AGATA_CON_RECLAMO');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'DELSAA';	
		NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.SCADA_AGATA_AFECTADO;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.SCADA_AGATA_AFECTADO');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	BEGIN
		PASO:= 'DELSAM';	
		NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.MODIFICA_DOCUMENTOS;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.MODIFICA_DOCUMENTOS');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;
	/*Desde aqui se agregan los nuevos procesos para cortes AT
		Modificado: RSLEIVA
		Fecha: 23/03/2023
		Nota: NECOPER-1031
	*/	
	BEGIN
		PASO:= 'CATIN';	
		NEXUS_GIS.INFORMACION_ENREMTAT.CORTESAT_INSERCION;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.CORTESAT_INSERCION');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;	
	BEGIN
		PASO:= 'CATUP';	
		NEXUS_GIS.INFORMACION_ENREMTAT.CORTESAT_ACTUALIZACION;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.CORTESAT_ACTUALIZACION');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;	
	BEGIN
		PASO:= 'CATNO';	
		NEXUS_GIS.INFORMACION_ENREMTAT.CORTESAT_NORMALIZACION;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.CORTESAT_NORMALIZACION');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;	
	BEGIN
		PASO:= 'CATEN';	
		NEXUS_GIS.INFORMACION_ENREMTAT.CORTESAT_INSERTA_DOC_DET;
	EXCEPTION WHEN OTHERS THEN
	  DBMS_OUTPUT.PUT_LINE ('Proceso en ejcución: NEXUS_GIS.ENRE_ELECTRODEPENDIENTES.CORTESAT_INSERTA_DOC_DET');
      DBMS_OUTPUT.PUT_LINE ('Error en proceso ' || SUBSTR (SQLERRM, 1, 100));
	END;	
	/*Fin NECOPER-1031*/
	DBMS_OUTPUT.PUT_LINE ('Proceso OK');
EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.PUT_LINE ('Error en proceso, paso= '||PASO||', con error: ' || SUBSTR (SQLERRM, 1, 100));
      
END;