SELECT * FROM NEXUS_GIS.TABLA_ENREMTAT_GEN WHERE NRO_DOCUMENTO='D-22-09-005342';
SELECT * FROM NEXUS_GIS.TABLA_ENREMTAT_DET WHERE NRO_DOCUMENTO='D-22-09-005342';




SELECT 
  doc.name
FROM 
  NEXUS_GIS.IDMS_DOCUMENTO_INFO IDOC, 
  NEXUS_GIS.OMS_DOCUMENT doc
WHERE 
  IDOC.ID_DOCUMENTO = DOC.ID
--  AND DOC.ID =10522011
  AND SUBSTR(DOC.NAME,1,7)='D-22-09'
  AND DOC.TYPE_ID IN (3,4)
  and idoc.evento_confirmado<>1
  
;