SELECT NAME, TEXT
FROM ALL_SOURCE
WHERE UPPER(TEXT) LIKE '%INSERT%LLAM_PEDIDO_INTS_MT%'
  AND TYPE IN ('FUNCTION', 'PROCEDURE', 'PACKAGE', 'PACKAGE BODY', 'VIEWS');

---------------------
SELECT * FROM NEXUS_GIS.LLAM_PEDIDO_INTS_MT P WHERE TO_DATE(FECHA_INICIO)>SYSDATE;
--UPDATE NEXUS_GIS.LLAM_PEDIDO_INTS_MT SET FECHA_INICIO='30/11/23' WHERE PEDIDO='MO-52485' AND CT='8133';

SELECT C.CUENTA, C.CT, C.* FROM NEXUS_CCYB.CLIENTES_CCYB C WHERE CT='8133';

-----------------

SELECT C.CUENTA, C.CT FROM NEXUS_CCYB.CLIENTES_CCYB C WHERE CT IN (SELECT CT FROM NEXUS_GIS.LLAM_PEDIDO_INTS_MT P WHERE TO_DATE(FECHA_INICIO)>SYSDATE);



