/*
select * from all_tables where owner='SVP_PLAN';
select * from r421_tabla_1_tmp;
select * from r421_tabla_1_tmp_osc;
select count(1) from svp_plan.r421_tabla_1_tmp_osc where nro_reclamo not in (
  select nro_reclamo from svp_plan.r421_tabla_1_tmp);
select column_name from all_tab_columns where table_name = 'svp_plan.r421_tabla_1_tmp_osc';
select * from all_tab_columns where table_name ='svp_plan.r421_tabla_1_tmp_osc';

NRO_RECLAMO, FECHA_RECLAMO, CALLE, NUMERO, ENTRE_CALLE_1, ENTRE_CALLE_2, BARRIO, LOCALIDAD, PARTIDO, ZONA, FECHA_INICIO, ID_SUBTIPO, VIA_RECLAMO, DETECTOR, BSERVACION, 


DECLARE

BEGIN
  dbms_output.put_line('Busca Diferencias por campo: nro_reclamo');
  for d in (select 'nro_reclamo' campo, count(1) cantidad from svp_plan.r421_tabla_1_tmp_osc where nro_reclamo not in (select nro_reclamo from svp_plan.r421_tabla_1_tmp))
  loop
    dbms_output.put_line('Campo nro_reclamo: ' || d.cantidad);
  END LOOP;

END;
*/

--TABLA 1

SELECT 'NRO_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE NRO_RECLAMO NOT IN (SELECT NRO_RECLAMO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'FECHA_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE TO_CHAR(FECHA_RECLAMO) NOT IN (SELECT TO_CHAR(FECHA_RECLAMO) FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'CALLE' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE CALLE NOT IN (SELECT CALLE FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'NUMERO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE NUMERO NOT IN (SELECT NUMERO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'ENTRE_CALLE_1' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE ENTRE_CALLE_1 NOT IN (SELECT ENTRE_CALLE_1 FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'ENTRE_CALLE_2' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE ENTRE_CALLE_2 NOT IN (SELECT ENTRE_CALLE_2 FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'BARRIO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE BARRIO NOT IN (SELECT BARRIO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'LOCALIDAD' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE LOCALIDAD NOT IN (SELECT LOCALIDAD FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'PARTIDO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE PARTIDO NOT IN (SELECT PARTIDO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'ZONA' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE ZONA NOT IN (SELECT ZONA FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'FECHA_INICIO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE TO_CHAR(FECHA_INICIO) NOT IN (SELECT TO_CHAR(FECHA_INICIO) FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'ID_SUBTIPO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE ID_SUBTIPO NOT IN (SELECT ID_SUBTIPO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'VIA_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE VIA_RECLAMO NOT IN (SELECT VIA_RECLAMO FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'DETECTOR' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE DETECTOR NOT IN (SELECT DETECTOR FROM SVP_PLAN.R421_TABLA_1_TMP);
SELECT 'OBSERVACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE OBSERVACION NOT IN (SELECT OBSERVACION FROM SVP_PLAN.R421_TABLA_1_TMP);


--correcciones

SELECT NRO_RECLAMO, CALLE FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE CALLE NOT IN (SELECT CALLE FROM SVP_PLAN.R421_TABLA_1_TMP) ORDER BY NRO_RECLAMO;
SELECT NRO_RECLAMO, CALLE FROM SVP_PLAN.R421_TABLA_1_TMP WHERE CALLE NOT IN (SELECT CALLE FROM SVP_PLAN.R421_TABLA_1_TMP_OSC) ORDER BY NRO_RECLAMO;

SELECT NRO_RECLAMO, OBSERVACION CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP_OSC WHERE OBSERVACION NOT IN (SELECT OBSERVACION FROM SVP_PLAN.R421_TABLA_1_TMP) ORDER BY NRO_RECLAMO;
SELECT NRO_RECLAMO, OBSERVACION CANTIDAD FROM SVP_PLAN.R421_TABLA_1_TMP WHERE OBSERVACION NOT IN (SELECT OBSERVACION FROM SVP_PLAN.R421_TABLA_1_TMP_OSC) ORDER BY NRO_RECLAMO;

--TABLA 2
/*
NRO_RECLAMO, 
FECHA_RECLAMO, 
ID_SUBTIPO, 
FECHA_NEUTRALIZACION, 
ACCION_ELIMINACION, 
FECHA_ELIMINACION, 
ACCION_NORMALIZACION, 
FECHA_NORMALIZACION, 
FECHA_ANULACION, 
ANULACION, 
ID_USUAR, 
COORD_X, 
COORD_Y, 
OBSERVACION, 
*/


SELECT 'NRO_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE NRO_RECLAMO NOT IN (SELECT NRO_RECLAMO FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'FECHA_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE TO_CHAR(FECHA_RECLAMO) NOT IN (SELECT TO_CHAR(FECHA_RECLAMO) FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'ID_SUBTIPO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE ID_SUBTIPO NOT IN (SELECT ID_SUBTIPO FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'FECHA_NEUTRALIZACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE TO_CHAR(FECHA_NEUTRALIZACION) NOT IN (SELECT TO_CHAR(FECHA_NEUTRALIZACION) FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'ACCION_ELIMINACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE ACCION_ELIMINACION NOT IN (SELECT ACCION_ELIMINACION FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'FECHA_ELIMINACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE TO_CHAR(FECHA_ELIMINACION) NOT IN (SELECT TO_CHAR(FECHA_ELIMINACION) FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'ACCION_NORMALIZACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE ACCION_NORMALIZACION NOT IN (SELECT ACCION_NORMALIZACION FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'FECHA_NORMALIZACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE TO_CHAR(FECHA_NORMALIZACION) NOT IN (SELECT TO_CHAR(FECHA_NORMALIZACION) FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'FECHA_ANULACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE TO_CHAR(FECHA_ANULACION) NOT IN (SELECT TO_CHAR(FECHA_ANULACION) FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'ANULACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE ANULACION NOT IN (SELECT ANULACION FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'ID_USUAR' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE ID_USUAR NOT IN (SELECT ID_USUAR FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'COORD_X' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE COORD_X NOT IN (SELECT COORD_X FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'COORD_Y' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE COORD_Y NOT IN (SELECT COORD_Y FROM SVP_PLAN.R421_TABLA_2_TMP);
SELECT 'OBSERVACION' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE OBSERVACION NOT IN (SELECT OBSERVACION FROM SVP_PLAN.R421_TABLA_2_TMP);


SELECT COUNT(1) FROM r421_tabla_2_tmp;      --10262 +79
SELECT COUNT(1) FROM r421_tabla_2_tmp_osc;  --10183 -79
'
SELECT 'NRO_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP_OSC WHERE NRO_RECLAMO NOT IN (SELECT NRO_RECLAMO FROM SVP_PLAN.R421_TABLA_2_TMP);

--NRO_RECLAMO DEFINITIVA TIENE +79
SELECT 'NRO_RECLAMO' CAMPO, COUNT(1) CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP WHERE NRO_RECLAMO NOT IN (SELECT NRO_RECLAMO FROM SVP_PLAN.R421_TABLA_2_TMP_OSC);
SELECT NRO_RECLAMO CANTIDAD FROM SVP_PLAN.R421_TABLA_2_TMP WHERE NRO_RECLAMO NOT IN (SELECT NRO_RECLAMO FROM SVP_PLAN.R421_TABLA_2_TMP_OSC);
-- LOS 79 RECLAMOS NO APARECIAN EN EL QUERI ORIGINAL DE GISPR01S
