set serveroutput on
declare

  v_r sisenre.cds5.ref%type;
  v_f sisenre.cds5.f%type;
  v_c sisenre.cds5.cli%type;
  v_ca sisenre.cds5.cadena%type;
  v_u sisenre.cds5.usuario%type;
  v_fo sisenre.cds5.fecha_oper%type;
  v_o sisenre.cds5.operacion%type;

begin

select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004260' and f=1 and cadena='4676#B1#4676-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206000083' and f=2 and cadena='50001#B1#50001-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003647' and f=1 and cadena='9167#B1#9167-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003653' and f=1 and cadena='9167#B1#9167-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003657' and f=1 and cadena='9167#B1#9167-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206002866' and f=1 and cadena='9218#B1#9218-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206083354' and f=2 and cadena='9236#B1#9236-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001919' and f=2 and cadena='9236#B1#9236-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001935' and f=1 and cadena='9236#B1#9236-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001937' and f=1 and cadena='9236#B1#9236-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206083352' and f=1 and cadena='11901#B1#11901-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206083352' and f=1 and cadena='16774#B1#16774-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206006277' and f=2 and cadena='34148#B1#34148-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206006280' and f=1 and cadena='34148#B1#34148-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001379' and f=1 and cadena='40416#B1#40416-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206005178' and f=1 and cadena='40416#B1#40416-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206005699' and f=3 and cadena='77221#B1#77221-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004167' and f=1 and cadena='77258#B1#77258-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206005750' and f=1 and cadena='8205#B1#8205-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001427' and f=1 and cadena='9033#B1#9033-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001436' and f=1 and cadena='9033#B1#9033-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001449' and f=1 and cadena='9033#B1#9033-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206002443' and f=1 and cadena='9033#B1#9033-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001427' and f=1 and cadena='9679#B1#9679-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001436' and f=1 and cadena='9679#B1#9679-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001449' and f=1 and cadena='9679#B1#9679-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206002443' and f=1 and cadena='9679#B1#9679-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206002452' and f=1 and cadena='9679#B1#9679-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206006269' and f=1 and cadena='11317#B1#11317-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004203' and f=1 and cadena='13246#B1#13246-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004235' and f=1 and cadena='13246#B1#13246-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206005655' and f=1 and cadena='16294#B1#16294-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206005701' and f=2 and cadena='16294#B1#16294-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206005769' and f=1 and cadena='16294#B1#16294-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206004154' and f=1 and cadena='18277#B1#18277-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206003180' and f=1 and cadena='3007#B1#3007-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206003768' and f=1 and cadena='33097#B1#33097-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001051' and f=1 and cadena='4046#B1#4046-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001053' and f=3 and cadena='4046#B1#4046-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206001998' and f=2 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206002004' and f=1 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206003277' and f=4 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003484' and f=1 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003488' and f=1 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003489' and f=2 and cadena='6071#B1#6071-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206083390' and f=1 and cadena='7335#B1#7335-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206083392' and f=1 and cadena='7335#B1#7335-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206002397' and f=2 and cadena='77163#B1#77163-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206005214' and f=1 and cadena='77163#B1#77163-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206002397' and f=2 and cadena='77726#B1#77726-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPO202206001454' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPO202206001893' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001455' and f=2 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003181' and f=2 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003219' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003264' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206004725' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206004777' and f=1 and cadena='8098#B1#8098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004151' and f=1 and cadena='13246#B1#13246-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206000083' and f=3 and cadena='50641#B1#50641-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004229' and f=3 and cadena='53098#B1#53098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206005222' and f=2 and cadena='53098#B1#53098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206006220' and f=2 and cadena='53098#B1#53098-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001005' and f=1 and cadena='6181#B1#6181-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='AFZ202206002397' and f=1 and cadena='77096#B1#77096-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004707' and f=1 and cadena='77716#B1#77716-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206004708' and f=2 and cadena='77716#B1#77716-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206002831' and f=1 and cadena='77748#B1#77748-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206003134' and f=1 and cadena='77748#B1#77748-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MPR202206001932' and f=1 and cadena='82011#B1#82011-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);
select ref, f, cli, cadena, usuario, fecha_oper, operacion into v_r, v_f, v_c, v_ca, v_u, v_fo, v_o from cds5 where ref='MFZ202206006288' and f=2 and cadena='82251#B1#82251-TR1'; dbms_output.put_line(v_r||'; '||v_f||'; '||v_c||'; '||v_ca||'; '||v_u||'; '||v_fo||'; '||v_o);

exception
  when no_data_found then
    dbms_output.put_line('No encontrado');

end;


