GRANT SELECT ON NEXUS_GIS.OMS_DOCUMENT_TYPE TO GELEC;



GRANT SELECT ON NEXUS_GIS.DSCCCLIENTPHONES TO GELEC;
GRANT SELECT ON NEXUS_GIS.DSCCPHONETYPES TO GELEC;
GRANT SELECT ON NEXUS_GIS.SMSTREETS TO GELEC;


GELEC_READ_ROLE  > SOLO SELECT
GELEC_ROLE > ACCIONES (SOLO SI GELEC MODIFICARIA, INSERTARIA O ELIMINARIA EN NEXUS_GIS)



[12:06] Vanesa Paola DI CIURCIO
GRANT SELECT ON NEXUS_GIS.WSENRE_GR_ELECTROGENOS_LOG TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSENRE_INFO_SAP TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WS_ENREMTAT_LOG TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSENRE_OBRAS_FOCEDE TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSENRE_PARTE_OBRAS TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSENRE_RECLAMOS TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSENRE_748_LOG TO NEXUSGIS_READ_ROLE;
GRANT SELECT ON NEXUS_GIS.WSEQUIPOTRABAJO TO NEXUSGIS_READ_ROLE;

[12:07] Vanesa Paola DI CIURCIO
GRANT NEXUSGIS_READ_ROLE TO TDONZIS;
GRANT NEXUSGIS_READ_ROLE TO VALEGOMEZ;
GRANT NEXUSGIS_READ_ROLE TO VAQUINTERO;
GRANT NEXUSGIS_READ_ROLE TO VDICIURCIO;
GRANT NEXUSGIS_READ_ROLE TO VURDININEA;
GRANT NEXUSGIS_READ_ROLE TO YGIL;

