--SOT-12481
--GELEC---------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM GELEC.ED_DOCUMENTOS WHERE FECHA_INICIO_DOC>FECHA_FIN_DOC;
SELECT * FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES WHERE FECHA_INICIO_CORTE>FECHA_FIN_CORTE ORDER BY ID_DOCUMENTO DESC;
SELECT ID_DOCUMENTO, CUENTA, COUNT(1) FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES 
WHERE FECHA_INICIO_CORTE>FECHA_FIN_CORTE 
GROUP BY ID_DOCUMENTO, CUENTA 
HAVING COUNT(1)>1
ORDER BY ID_DOCUMENTO DESC 
;  
SELECT ID_DOCUMENTO, ID_DOC_CLIENTE, CUENTA, FECHA_INICIO_CORTE, FECHA_FIN_CORTE FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES 
WHERE ID_DOCUMENTO=10059127 AND CUENTA='0519048141'
ORDER BY ID_DOCUMENTO, CUENTA, ID_DOC_CLIENTE
;

--OMS-----------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM ALL_TABLES WHERE OWNER='NEXUS_GIS' AND TABLE_NAME LIKE '%OMS%' ORDER BY TABLE_NAME;

SELECT * FROM NEXUS_GIS.OMS_CLAIM_HISTORY WHERE DOCUMENT=10059127;
SELECT * FROM NEXUS_GIS.OMS_CLAIM_MOVEMENT_HISTORY WHERE DOCUMENT_ID_TO=10059127;
SELECT * FROM NEXUS_GIS.OMS_CLAIM_CLOSE WHERE ID=10059127;

