SELECT 
  M.ID, 
  M.CUENTA, 
  (SELECT DESCRIPCION FROM GELEC.ED_MARCAS WHERE ID=M.ID_MARCA) MARCA,
  (SELECT DESCRIPCION FROM GELEC.ED_SUBMARCAS WHERE ID_SUBMARCA=M.ID_SUBMARCA) SUBMARCA,
  L.FECHA
FROM 
  GELEC.ED_MARCA_CLIENTE M,
  GELEC.ED_LOG L
WHERE 
  M.LOG_DESDE=L.LOG_ID
  AND M.ID_SUBMARCA IN (7,8,9,10,13,14,15,16)
  AND NVL(M.LOG_HASTA,0)=0
  AND TO_CHAR(L.FECHA,'YYYY')<>2022
;




SELECT * FROM GELEC.ED_MARCAS;
SELECT * FROM GELEC.ED_SUBMARCAS;
SELECT * FROM GELEC.ED_LOG;