DECLARE
  v_doc GELEC.ED_DOCUMENTOS.NRO_DOCUMENTO%Type;
  v_cta GELEC.ED_DET_DOCUMENTOS_CLIENTES.CUENTA%Type;
  v_nom GELEC.ED_CLIENTES.NOMBRE%Type;
  v_dir VARCHAR2(200);
  v_zon GELEC.ED_DOCUMENTOS.ZONA%Type;
  v_reg GELEC.ED_DOCUMENTOS.REGION%Type;
  v_cts GELEC.ED_DET_DOCUMENTOS_CLIENTES.CT_CLIE%Type;
  v_alm GELEC.ED_CLIENTES.ALIMENTADOR%Type;
  v_sse GELEC.ED_CLIENTES.SSEE%Type;
  v_fin GELEC.ED_DOCUMENTOS.FECHA_INICIO_DOC%Type;
  v_ffn GELEC.ED_DOCUMENTOS.FECHA_FIN_DOC%Type;

  CURSOR REP IS (
      SELECT 
        D.NRO_DOCUMENTO DOC, 
        DC.CUENTA, 
        C.RAZON_SOCIAL NOMBRE, 
        TRIM(C.CALLE ||' '|| C.NRO ||' '|| TRIM(C.PISO_DPTO)) DIRECCION, 
        UPPER(D.ZONA) ZONA, 
        D.REGION, 
        DC.CT_CLIE CT, 
        C.ALIMENTADOR, 
        C.SSEE, 
        TO_CHAR(D.FECHA_INICIO_DOC,'DD/MM/YYYY HH24:MM:SS') FINI, 
        TO_CHAR(D.FECHA_FIN_DOC,'DD/MM/YYYY HH24:MM:SS') FFIN
      FROM 
        GELEC.ED_DOCUMENTOS D, 
        GELEC.ED_DET_DOCUMENTOS_CLIENTES DC,
        GELEC.ED_CLIENTES C
      WHERE
        1=1
        AND D.ID_DOCUMENTO=DC.ID_DOCUMENTO
        AND DC.CUENTA=C.CUENTA
        AND D.TIPO_CORTE='Forzado MT'
        AND D.FECHA_INICIO_DOC>='01/06/2021'
        AND D.FECHA_FIN_DOC<='01/07/2022'
      ORDER BY D.FECHA_INICIO_DOC ASC
    );
    
BEGIN
    
  
END;