SELECT 
  MC.CUENTA,
  C.REGION, 
  C.PARTIDO, 
  C.LOCALIDAD, 
  (SELECT DESCRIPCION FROM GELEC.ED_MARCAS WHERE ID=MC.ID_MARCA) MARCA, 
  (SELECT DESCRIPCION FROM GELEC.ED_SUBMARCAS WHERE ID_SUBMARCA=MC.ID_SUBMARCA) SUBMARCA, 
  (SELECT FECHA FROM GELEC.ED_LOG WHERE LOG_ID=MC.LOG_DESDE) FECHA_INICIO,
  (SELECT FECHA FROM GELEC.ED_LOG WHERE LOG_ID=MC.LOG_HASTA) FECHA_FIN,
  CASE WHEN N.OBSERVACIONES='Marca Baja Potencial Automatica' THEN 'Automatica' ELSE 'Manual' END DECODE,
  N.OBSERVACIONES
FROM 
  GELEC.ED_MARCA_CLIENTE MC, 
  GELEC.ED_NOTAS N, 
  GELEC.ED_CLIENTE_NOTA CN, 
  GELEC.ED_CLIENTES C
WHERE 
  MC.ID_MARCA=1
  AND NVL(MC.LOG_HASTA,0)=0
  AND N.ID_NOTA=CN.ID_NOTA AND CN.CUENTA=MC.CUENTA
  AND MC.CUENTA=C.CUENTA
  AND N.OBSERVACIONES LIKE '%Baja Potencial%'
ORDER BY
  MC.ID DESC
;

/*
SELECT * FROM GELEC.ED_MARCAS;
SELECT * FROM GELEC.ED_SUBMARCAS;
SELECT * FROM GELEC.ED_MARCA_CLIENTE WHERE ID_MARCA=1;
SELECT * FROM GELEC.ED_LOG;
SELECT * FROM GELEC.ED_NOTAS;
SELECT * FROM GELEC.ED_CLIENTE_NOTA;
SELECT * FROM GELEC.ED_CLIENTES;
*/
