--GRANT SELECT ON NEXUS_GIS.SPROBJECTS TO GELEC;
--GRANT SELECT ON GELEC.ED_CLIENTES TO NEXUS_GIS;
--GRANT EXECUTE ON NEXUS_GIS.INFORMACION_ENREMTAT TO GELEC;

SELECT
  CC.CUENTA CUENTA
  ,D.CREATION_TIME FECHA_INICIO
  ,NEXUS_GIS.INFORMACION_ENREMTAT_DIN.FECHA_RESTAURACION(D.ID,AE.ELEMENT_ID) FECHA_RESTAURACION
  ,CC.RAZON_SOCIAL
  ,D.ID DOCUMENTO
  ,(SELECT MAX(ID) FROM NEXUS_GIS.OMS_CLAIM WHERE DOCUMENT_ID=D.ID AND PROPERTY_VALUE=CC.CUENTA) RECLAMO
  ,'AF' ORIGEN
  ,AE.ID ID_AFECTACION 
  ,NEXUS_GIS.INFORMACION_ENREMTAT_DIN.CT_FROM_OBJECTID(AE.ELEMENT_ID) CT
FROM 
  NEXUS_GIS.OMS_DOCUMENT D
  ,NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO
  ,NEXUS_GIS.OMS_AFFECTED_ELEMENT AE
  ,GELEC.ED_CLIENTES CC
WHERE
  1=1
  AND D.ID=ARO.DOCUMENT_ID
  AND ARO.ID=AE.AFFECT_ID
  AND D.LAST_STATE_ID<5
  AND NEXUS_GIS.INFORMACION_ENREMTAT_DIN.CT_FROM_OBJECTID(AE.ELEMENT_ID)=CC.CT
  AND D.TYPE_ID IN (3,4)
  AND ARO.IS_RESTORE=0
  AND ARO.OPERATION_ID IS NOT NULL
  
;  



SELECT * FROM NEXUS_GIS.SPRCLIENTS;
SELECT * FROM NEXUS_CCYB.CLIENTES_CCYB;
SELECT * FROM GELEC.ED_CLIENTES;
select * from NEXUS_GIS.SPRLinks where objectid=17574563 and linkid in (611);