DECLARE
    CURSOR C_CADENA IS (
          SELECT 
              T52.ID_USUAR,
              T52.CEN_MTBT CT52,
              T51.CEN_MTBT CT51
          --    SUBSTR(T52.CEN_MTBT,1,INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',1)+1)+1)) CI52,
          --    SUBSTR(T51.CEN_MTBT,1,INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',1)+1)+1)) CI51,
          --    SUBSTR(T52.CEN_MTBT,INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',1)+1)+1),LENGTH(T52.CEN_MTBT)) CD52,
          --    SUBSTR(T51.CEN_MTBT,INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',1)+1)+1),LENGTH(T51.CEN_MTBT)) CD51
          FROM 
              SISENRE.CDS10_SEM T52,
              (SELECT T52.ID_USUAR, T52.CEN_MTBT FROM SISENRE.CDS10_SEM T52 WHERE T52.PERIODO='SEM_51' AND LENGTH(T52.CEN_MTBT)- LENGTH(REPLACE(T52.CEN_MTBT,'#',''))=4) T51
          WHERE 
              T52.ID_USUAR=T51.ID_USUAR
              AND T52.PERIODO='SEM_52'
              AND LENGTH(T52.CEN_MTBT)- LENGTH(REPLACE(T52.CEN_MTBT,'#',''))=4
              AND ROWNUM<10
              AND
                  SUBSTR(T52.CEN_MTBT,1,INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',1)+1)+1)) 
                  =
                  SUBSTR(T51.CEN_MTBT,1,INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',1)+1)+1)) 
              AND
                  SUBSTR(T52.CEN_MTBT,INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',INSTR(T52.CEN_MTBT,'#',1)+1)+1),LENGTH(T52.CEN_MTBT)) 
                  <>
                  SUBSTR(T51.CEN_MTBT,INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',INSTR(T51.CEN_MTBT,'#',1)+1)+1),LENGTH(T51.CEN_MTBT)) 
      );
      
BEGIN
    FOR F_CUR IN C_CADENA LOOP
    
          DBMS_OUTPUT.PUT_LINE('UPDATE SISENRE.CDS10_SEM SET CEN_MTBT= '||F_CUR.CT51||' WHERE ID_USUAR= '||F_CUR.ID_USUAR||' AND CEN_MTBT='||F_CUR.CT52||' AND PERIODO= ''SEM_52'';');
    
--        UPDATE SISENRE.CDS10_SEM SET CEN_MTBT= F_CUR.CT51 WHERE ID_USUAR= F_CUR.ID_USUAR AND CEN_MTBT=F_CUR.CT52 AND PERIODO= 'SEM_52';        
--        COMMIT;
    
    END LOOP;
END;