SELECT 
  CC.CUENTA, 
  CT.CODIGOCT, 
  CT.CTTRAFO,
  CT.CODIGOALIM,
  CT.CODIGOSSEE, 
  CT.NOMBRESSEE,
  CT.BARRA, 
  NULL TABLERO, 
  NULL SALIDA, 
  (SELECT S.REGION FROM NEXUS_GIS.SPRCLIENTS C, NEXUS_GIS.LLAM_SECTORES S WHERE C.LOGIDTO = 0 AND C.LEVELONEAREAID=S.LOCA_ID AND C.FSCLIENTID=CC.CUENTA) REGION,
  UPPER((SELECT Z.ZONA FROM NEXUS_GIS.SPRCLIENTS S, NEXUS_GIS.PARTIDO_ZONA Z WHERE S.FSCLIENTID=CC.CUENTA AND S.LEVELTWOAREAID=Z.AREAID)) ZONA, 
  (SELECT S.SECTOR FROM NEXUS_GIS.SPRCLIENTS C, NEXUS_GIS.LLAM_SECTORES S WHERE C.LOGIDTO = 0 AND C.LEVELONEAREAID=S.LOCA_ID AND C.FSCLIENTID=CC.CUENTA) SECTOR,
  (SELECT S.PARTIDO FROM NEXUS_GIS.SPRCLIENTS C, NEXUS_GIS.LLAM_SECTORES S WHERE C.LOGIDTO = 0 AND C.LEVELONEAREAID=S.LOCA_ID AND C.FSCLIENTID=CC.CUENTA) PARTIDO,
  (SELECT S.LOCALIDAD FROM NEXUS_GIS.SPRCLIENTS C, NEXUS_GIS.LLAM_SECTORES S WHERE C.LOGIDTO = 0 AND C.LEVELONEAREAID=S.LOCA_ID AND C.FSCLIENTID=CC.CUENTA) LOCALIDAD,
  (SELECT S.AREA_GEST FROM NEXUS_GIS.SPRCLIENTS C, NEXUS_GIS.LLAM_SECTORES S WHERE C.LOGIDTO = 0 AND C.LEVELONEAREAID=S.LOCA_ID AND C.FSCLIENTID=CC.CUENTA) AREA_TECNICA
FROM 
  NEXUS_CCYB.CLIENTES_CCYB CC,
  NEXUS_CCYB.CADENA_CT CT
WHERE
  CC.CT=CT.CODIGOCT
  AND CC.FECHABAJA>SYSDATE
;



SELECT 
  s.*
FROM 
  NEXUS_GIS.SPRCLIENTS C,
  nexus_gis.LLAM_SECTORES s
WHERE 
  C.LOGIDTO = 0
  AND C.LEVELONEAREAID=S.LOCA_ID
;








