SELECT LC.LINKVALUE CUENTA, SUBSTR(LT.LINKVALUE, 1, INSTR(LT.LINKVALUE,'-')-1) CT, INSTR(LT.LINKVALUE,'-')-1 POSICION
FROM 
  NEXUS_GIS.NBM_RELATION R, 
  NEXUS_GIS.SPROBJECTS OC, 
  NEXUS_GIS.SPRLINKS LC, 
  NEXUS_GIS.SPROBJECTS OT, 
  NEXUS_GIS.SPRLINKS LT
WHERE
      1=1
  AND LC.OBJECTID=OC.OBJECTID
  AND OC.OBJECTNAMEID=R.OBJECT_NAME_ID_TO
  AND R.OBJECT_NAME_ID_FROM=OT.OBJECTNAMEID
  AND OT.OBJECTID=LT.OBJECTID
  AND R.CONFIGURATION_ID=1 AND R.STATUS=0
  AND LC.LOGIDTO=0 AND LC.LINKID=407
  AND OC.SPRID=190 AND OC.LOGIDTO=0
  AND OT.SPRID=1170 AND OT.LOGIDTO=0
  AND LT.LOGIDTO=0 AND LT.LINKID=611
--  and lc.linkvalue in ('0068834943')
  AND SUBSTR(LT.LINKVALUE, 1, INSTR(LT.LINKVALUE,'-')-1) IN ('82001')
;