SELECT ID FROM NEXUS_GIS.OMS_DOCUMENT WHERE NAME='D-22-12-015570';
SELECT * FROM NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION WHERE DOCUMENT_ID=10649020 AND IS_RESTORE=0 AND OPERATION_ID IS NOT NULL;
SELECT FSCLIENTID, CUSTATT16, CUSTATT21 FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID='0353734224' AND CUSTATT16='1A';
SELECT * FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID='0353734224' and custatt16='1A';
16739046

SELECT 
  d.fsclientid, d.fullname
FROM 
  NEXUS_GIS.NBM_RELATION A, 
  NEXUS_GIS.SPROBJECTS B, 
  NEXUS_GIS.SPRLINKS C, 
  nexus_gis.sprclients D
WHERE 
  A.CONFIGURATION_ID=47 
  AND A.OBJECT_NAME_ID_FROM=B.OBJECTNAMEID 
  AND B.LOGIDTO=0 AND B.SPRID=190 
  AND B.OBJECTID=C.OBJECTID 
  AND C.LOGIDTO=0 
  AND C.LINKID=407 
  and a.object_name_id_to in (
      SELECT B.OBJECTNAMEID 
      FROM NEXUS_GIS.SPRLINKS A, NEXUS_GIS.SPROBJECTS B, NEXUS_GIS.NBM_RELATION C 
      WHERE A.LINKID=410 
      AND A.OBJECTID=B.OBJECTID 
      and b.sprid=1113
      AND B.OBJECTNAMEID=C.OBJECT_NAME_ID_FROM 
      and c.configuration_id=41
      and a.logidto=0 and b.logidto=0
      and c.object_name_id_to = (
          select d.objectnameid
          FROM NEXUS_GIS.SPROBJECTS A, NEXUS_GIS.SPRLINKS B, NEXUS_GIS.SPRLINKS C, NEXUS_GIS.SPROBJECTS D
          WHERE 1=1
          and A.OBJECTNAMEID=61806416 
          AND A.SPRID=1293 
          and a.logidto=0
          AND A.OBJECTID=B.OBJECTID 
          AND B.LINKID=1018 
          and b.logidto=0
          AND B.LINKVALUE=C.LINKVALUE 
          AND C.LOGIDTO=0 
          AND C.LINKID=611
          AND C.OBJECTID=D.OBJECTID 
          AND D.LOGIDTO=0 
          AND D.SPRID=1170
      )
  )
--  AND C.OBJECTID=to_number(D.CUSTATT2)
  and trim(c.linkvalue)=d.fsclientid
  AND D.CUSTATT16='1A'
  AND D.CUSTATT21=12521
  and d.logidto=0
;
