SELECT ARO.DOCUMENT_ID, AE.COUNT_PROPERTIES 
FROM 
  NEXUS_GIS.OMS_AFFECTED_ELEMENT AE
  , NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO
  , NEXUS_GIS.OMS_DOCUMENT D
WHERE
  D.ID=ARO.DOCUMENT_ID
  AND ARO.ID=AE.AFFECT_ID
  AND SUBSTR(D.NAME,1,7)='D-22-09'
  
;  