--NO CONFIRMADO NI DELTA
SELECT 
  ARO.DOCUMENT_ID, 
  TRIM(SUBSTR(L.LINKVALUE,1,INSTR(L.LINKVALUE,'-')-1)) CT, 
  (SELECT COUNT(1) FROM NEXUS_CCYB.CLIENTES_CCYB WHERE CT=TRIM(SUBSTR(L.LINKVALUE,1,INSTR(L.LINKVALUE,'-')-1)) AND FECHABAJA<SYSDATE) CLIENTES
FROM 
  NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO, 
  NEXUS_GIS.OMS_AFFECTED_ELEMENT AE, 
  NEXUS_GIS.SPROBJECTS O,
  NEXUS_GIS.SPRLINKS L,
  NEXUS_GIS.OMS_DOCUMENT D,
  NEXUS_GIS.OMS_ADDRESS A
WHERE
  ARO.ID=AE.AFFECT_ID
  AND AE.ELEMENT_ID=O.OBJECTNAMEID
  AND O.OBJECTID=L.OBJECTID
  and ARO.DOCUMENT_ID in (SELECT 
                  doc.id
                FROM 
                  NEXUS_GIS.IDMS_DOCUMENTO_INFO IDOC, 
                  NEXUS_GIS.OMS_DOCUMENT doc
                WHERE 
                  IDOC.ID_DOCUMENTO = DOC.ID
                  AND DOC.ID =10475943
                  AND SUBSTR(DOC.NAME,1,7)='D-22-09'
                  AND DOC.TYPE_ID IN (3,4)
                  AND IDOC.EVENTO_CONFIRMADO<>1)  
  AND L.LOGIDTO=0
  AND L.LINKID=1018
  AND ARO.IS_RESTORE=0
  AND ARO.OPERATION_ID IS NOT NULL
  AND ARO.DOCUMENT_ID=D.ID
  AND D.ADDRESS_ID=A.ID
  AND (A.SMALL_AREA_ID<>435 AND A.MEDIUM_AREA_ID<>334)
;  


select * from NEXUS_CCYB.CLIENTES_CCYB where ct='11001';